import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '../widgets/header/ui/Header'
import Hero from '../widgets/hero/ui/Hero'
import AboutUs from '../widgets/aboutUs/ui/AboutUs'
import QuestionsSection from '../widgets/questionsSection/ui/QuestionsSection'
import ProductCardUI from '../entities/productCard/ui/ProductCardUI'
import { TestSection } from '../widgets/testSection/ui/TestSection'
import CatalogSection from '../widgets/catalog/ui/CatalogSection'
import OurClients from '../widgets/ourClients/ui/OurClients'
import { Footer } from '../widgets/footer'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Online-store',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
		<Header/>
		<Hero/>
		<AboutUs/>
		<TestSection/>
		<CatalogSection/>
		<QuestionsSection/>
		<OurClients/>
		<Footer/>
        {children}
      </body>
    </html>
  );
}
