import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../widgets/header/ui/Header";
import Footer from "../widgets/footer/ui/Footer";
import Reviews from "../widgets/reviews/ui/Reviews";
import ReviewCard from "../entities/reviewCard/ui/ReviewCard";
import Hero from "../widgets/hero/ui/Hero";
import AboutUs from "../widgets/aboutUs/ui/AboutUs";
import ReviewsCard from "../entities/reviewsCard/ui/ReviewsCard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Online-store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh",
          }}
        >
          {/* <Header />
          <Hero />
          <AboutUs />
          <TestSection /> */}
          <div style={{ flex: 1 }}></div>
          {/* <Footer /> */}
        </div>
        {children}
      </body>
    </html>
  );
}
